### ISSUE TITLE
Add auto formatter for C# code

### ISSUE THREAD

**Issue by rruiter87** [Roald87/TcBlack#90]
https://github.com/belav/csharpier

1. install CSharpier
    - `dotnet tool install csharpier -g`
2. Add to `pre-commit-config.yaml`
  
    ```yaml
      - repo: local
        hooks:
          - id: CSharpier
            name: Format C# files
            entry: dotnet csharpier
            language: system
            files: '.*\.(cs$)'
    ```
3. run `pre-commit run --all-files` once
